name: 'CI'

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: open-turo/actions-gha/lint@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all

  # Check the caching feature.
  test-caching:
    name: Test caching
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: First Download
        uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
      - name: Second Download
        uses: ./
        id: second-setup
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
      - name: Checked catched or not
        if: steps.second-setup.outputs.restore-from-cache == 'false'
        run: exit 1

  # Check the caching feature.
  test-no-caching:
    name: Test no caching
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: First Download
        uses: ./
        id: first-setup
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
      - name: Checked catched or not
        if: steps.first-setup.outputs.restore-from-cache == 'true'
        run: exit 1

  # Check if it can install the latest release.
  test-latest-linux-amd64:
    name: Get latest linux amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
      - run: setup-release-test-repo-public

  # Check if it can install specific release.
  test-tagged-linux-amd64:
    name: Get v0.1.0 linux amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
          tag: v0.1.0
      - run: setup-release-test-repo-public

  # Check if there are no problem installing the same release twice.
  test-multiple-install:
    name: Get latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
      - uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public

  # Check if it can install public repos in the wild (Part 1).
  test-public-repo-1:
    name: Get spinaker/kleat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        with:
          repository: spinnaker/kleat
      - run: kleat version

  # Check if it can install public repos in the wild (Part 2).
  test-public-repo-2:
    name: Get actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./
        with:
          repository: rhysd/actionlint
      - run: actionlint -version
